#!/bin/bash
# Colocar en: /usr/bin
source textoColor.sh

# Mostrar la fecha actual
texColor "+-------------------------------------------+" blue
texColor "|             ⏰ PROGRAMAR APAGADO          |" green
texColor "+-------------------------------------------+" blue
date
printf "\n"

# Solicitar la hora de apagado o reinicio
texColor "Ingrese la hora en formato hh:mm: " yellow
read -r hora

# Solicitar si se desea apagar o reiniciar
texColor "(1) Apagar o (2) Reiniciar: " yellow
read -r opcion

# Ejecutar la opción seleccionada
case $opcion in
  1)
    # Apagar el sistema
    sudo shutdown -h "$hora" "⚠️  Guarde su trabajo, la PC se apagará a las $hora."
    texColor "✅ Apagado programado exitosamente para las $hora." green
    ;;
  2)
    # Reiniciar el sistema
    sudo shutdown -r "$hora" "⚠️  Guarde su trabajo, la PC se reiniciará a las $hora."
    texColor "✅ Reinicio programado exitosamente para las $hora." green
    ;;
  *)
    # Manejar opción no válida
    texColor "❌ OPCIÓN NO VÁLIDA. Intente nuevamente." rojo
    ;;
esac

texColor "---------------------------------------------" blue
