#!/bin/bash
# Colocar en: /usr/bin

# Función para mostrar texto con colores
function texColor(){
    mensaje="$1"
    tipo="$2"
    colores=(31 32 33 34 35)
    nombres=('rojo' 'verde' 'amarillo' 'azul' 'morado')

    for i in "${!nombres[@]}"; do
        if [[ $tipo == "${nombres[i]}" ]]; then
            echo -e "\e[${colores[i]}m${mensaje}\e[0m"
        fi
    done
}

# Mostrar la fecha actual
texColor "---------------------------------------------" azul
texColor "             ⏰ PROGRAMAR APAGADO             " verde
texColor "---------------------------------------------" azul
date
printf "\n"

# Solicitar la hora de apagado o reinicio
texColor "Ingrese la hora en formato hh:mm: " amarillo
read -r hora

# Solicitar si se desea apagar o reiniciar
texColor "(1) Apagar o (2) Reiniciar: " amarillo
read -r opcion

# Ejecutar la opción seleccionada
case $opcion in
  1)
    # Apagar el sistema
    sudo shutdown -h "$hora" "⚠️  Guarde su trabajo, la PC se apagará a las $hora."
    texColor "✅ Apagado programado exitosamente para las $hora." verde
    ;;
  2)
    # Reiniciar el sistema
    sudo shutdown -r "$hora" "⚠️  Guarde su trabajo, la PC se reiniciará a las $hora."
    texColor "✅ Reinicio programado exitosamente para las $hora." verde
    ;;
  *)
    # Manejar opción no válida
    texColor "❌ OPCIÓN NO VÁLIDA. Intente nuevamente." rojo
    ;;
esac

texColor "---------------------------------------------" azul
