#!/bin/bash
# Colocar en: /usr/bin

# Función para mostrar texto con colores
function texColor() {
    mensaje="$1"
    tipo="$2"
    
    declare -A colores=(
        [red]=31
        [green]=32
        [yellow]=33
        [blue]=34
        [purple]=35
    )
    
    if [[ ${colores[$tipo]} ]]; then
        echo -e "\e[${colores[$tipo]}m${mensaje}\e[0m"
    fi
}

# Verificar el sistema operativo
os=$(grep '^ID=' /etc/os-release | cut -d= -f2)

# Limpiar la pantalla
clear

# Actualizar el sistema según la distribución
case "$os" in
    fedora)
        texColor '+-------------------------------------+' green
        texColor '|     𝙇𝙄𝙎𝙏𝘼 𝘿𝙀 𝘼𝘾𝙏𝙐𝘼𝙇𝙄𝙕𝘼𝘾𝙄𝙊𝙉𝙀𝙎 𝘿𝙉𝙁    |' green
        texColor '+-------------------------------------+' green
        printf "\n"
        sudo dnf update -y
    ;;
    arch)
        texColor '+-------------------------------------+' green
        texColor '|     𝙇𝙄𝙎𝙏𝘼 𝘿𝙀 𝘼𝘾𝙏𝙐𝘼𝙇𝙄𝙕𝘼𝘾𝙄𝙊𝙉𝙀𝙎 𝙋𝘼𝘾𝙈𝘼𝙉    |' green
        texColor '+-------------------------------------+' green
        printf "\n"
        sudo pacman -Syu --noconfirm
    ;;
    ubuntu|debian)
        texColor '+-------------------------------------+' green
        texColor '|     𝙇𝙄𝙎𝙏𝘼 𝘿𝙀 𝘼𝘾𝙏𝙐𝘼𝙇𝙄𝙕𝘼𝘾𝙄𝙊𝙉𝙀𝙎 𝘼𝙋𝙏    |' green
        texColor '+-------------------------------------+' green
        printf "\n"
        sudo apt update && sudo apt upgrade -y
    ;;
    *)
        texColor '✗ Sistema operativo no soportado.' red
        exit 1
    ;;
esac

# Separador
texColor '▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄' green
printf "\n"

# Actualizar Flatpak
texColor '+-------------------------------------+' blue
texColor '|  𝙇𝙄𝙎𝙏𝘼 𝘿𝙀 𝘼𝘾𝙏𝙐𝘼𝙇𝙄𝙕𝘼𝘾𝙄𝙊𝙉𝙀𝙎 𝙁𝙇𝘼𝙏𝙋𝘼𝙆   |' blue
texColor '+-------------------------------------+' blue
printf "\n"
flatpak update -y
texColor '▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄' blue
printf "\n"

# Actualizar Snap
texColor '+-------------------------------------+' red
texColor '|     𝙇𝙄𝙎𝙏𝘼 𝘿𝙀 𝘼𝘾𝙏𝙐𝘼𝙇𝙄𝙕𝘼𝘾𝙄𝙊𝙉𝙀𝙎 𝙎𝙉𝘼𝙋   |' red
texColor '+-------------------------------------+' red
printf "\n"
sudo snap refresh
texColor '▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄' red
printf "\n"
