#!/bin/bash
# Colocar en: /usr/bin

source textoColor.sh

# Función para imprimir líneas de separación
function separar() {
    local color="$1"
    texColor "-------------------------------------------" "$color"
}

# Extracción de archivos
if [ $# -ne 0 ]; then
    separar blue
    texColor "📁 Extracción de archivos" blue
    separar blue
    printf "\n\n"
    
    case $1 in
        *.tar.bz2)
            texColor "Extrayendo $1 con tar.bz2..." yellow
            tar xvjf "$1"
        ;;
        *.tar.gz)
            texColor "Extrayendo $1 con tar.gz..." yellow
            tar xvzf "$1"
        ;;
        *.tar.xz)
            texColor "Extrayendo $1 con tar.xz..." yellow
            tar xf "$1"
        ;;
        *.bz2)
            texColor "Extrayendo $1 con bunzip2..." yellow
            bunzip2 "$1"
        ;;
        *.rar)
            texColor "Extrayendo $1 con unrar..." yellow
            unrar x "$1"
        ;;
        *.gz)
            texColor "Extrayendo $1 con gunzip..." yellow
            gunzip "$1"
        ;;
        *.tar)
            texColor "Extrayendo $1 con tar..." yellow
            tar xvf "$1"
        ;;
        *.tbz2)
            texColor "Extrayendo $1 con tar.bz2..." yellow
            tar xvjf "$1"
        ;;
        *.tgz)
            texColor "Extrayendo $1 con tar.gz..." yellow
            tar xvzf "$1"
        ;;
        *.zip)
            texColor "Extrayendo $1 con unzip..." yellow
            unzip "$1"
        ;;
        *.Z)
            texColor "Extrayendo $1 con uncompress..." yellow
            uncompress "$1"
        ;;
        *.7z)
            texColor "Extrayendo $1 con 7z..." yellow
            7z x "$1"
        ;;
        *)
            texColor "✗ No se puede extraer el archivo ${1}." red
            separar red
            exit 1
        ;;
    esac
    
    printf "\n"
    separar green
    texColor "√ Extracción finalizada correctamente." green
    separar green
else
    separar red
    texColor "✗ Debe proporcionar un archivo para extraer." red
    separar red
fi
