#!/bin/bash
# Colocar en: /usr/bin
source textoColor.sh

# Verificar si el script se ejecuta con privilegios de superusuario
if [[ $EUID -ne 0 ]]; then
   echo -e "\e[31mEste script debe ejecutarse con privilegios de superusuario (sudo).\e[0m"
   exit 1
fi

# Limpiar la memoria caché
texColor "========== Limpiando la memoria caché ==========" yellow
sync # Sincroniza los datos pendientes de escribir en disco
echo 1 > /proc/sys/vm/drop_caches
texColor "✔️ Memoria caché limpiada correctamente." green

# Limpiar la memoria swap
texColor "========== Reiniciando la memoria swap ==========" yellow
swapoff -a
swapon -a
texColor "✔️ Memoria swap reiniciada correctamente." green

# Mostrar el estado de la memoria después de la limpieza
texColor "========== Estado de la memoria ==========" blue
free -h
texColor "✔️ Operación completada con éxito." green
