#! /bin/sh
#Colocar en: /usr/bin
clear
echo -e "\e[31m+-------------------------------------+\e[0m"
echo -e "\e[31m|     LISTA DE ACTUALIZACIONES DNF    |\e[0m"
echo -e "\e[31m+-------------------------------------+\e[0m"
echo "";
dnf update $1
echo -e "\e[1;34m<------------------------------------->\e[0m"
echo -e "\e[31m+-------------------------------------+\e[0m"
echo -e "\e[31m|   LISTA DE ACTUALIZACIONES FLATPAK  |\e[0m"
echo -e "\e[31m+-------------------------------------+\e[0m"
echo "";
flatpak update $1
echo -e "\e[1;34m<------------------------------------->\e[0m"
echo -e "\e[31m+-------------------------------------+\e[0m"
echo -e "\e[31m|    LISTA DE ACTUALIZACIONES SNAP    |\e[0m"
echo -e "\e[31m+-------------------------------------+\e[0m"
echo "";
snap refresh
echo -e "\e[1;34m<------------------------------------->\e[0m"
echo "";
echo "";


